name: Aggiorna playlist

on:
  schedule:
    - cron: '0 * * * *'  # ogni ora
  workflow_dispatch:      # esecuzione manuale

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Installa libreria requests
      run: pip install requests

    - name: Esegui script aggiornamento
      run: python update_playlist.py

    - name: Configura git per push con GITHUB_TOKEN
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/vroomvroomO/tf.git

    - name: Commit e push lista aggiornata
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add playlist_aggiornata.m3u
        git commit -m "Aggiorna playlist TF1 e TFX" || echo "Nessuna modifica"
        git push origin HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
