name: Aggiorna playlist TF1 TFX

on:
  schedule:
    - cron: '0 * * * *'   # ogni ora all'inizio dell'ora
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Installa requests
      run: pip install requests

    - name: Esegui aggiornamento playlist
      run: python update_playlist.py

    - name: Commit e push lista aggiornata
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add playlist_aggiornata.m3u
        git commit -m "Aggiorna playlist TF1 e TFX" || echo "Nessuna modifica"
        git push
