name: Aggiorna playlist da ParaTV

on:
  schedule:
    - cron: '17 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with: { python-version: '3.x' }

    - name: Installa requests
      run: pip install requests

    - name: Esegui script aggiornamento
      run: python update_playlist.py

    - name: Configura git per push
      run: git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/vroomvroomO/tf.git

    - name: Commit & push playlist aggiornata
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add playlist_aggiornata.m3u
        git commit -m "Aggiornamento canali TF1/TMC/Arte ecc." || echo "Nessuna modifica"
        git push origin HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
